name: Update playlist with Spotify Auth

on:
  push:
    branches:
      - main

jobs:
  spotify_auth_and_apply:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Spotify Auth Proxy
        run: |
          docker run -d --name spotify-auth-proxy \
          -p 27228:27228 \
          -e SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} \
          -e SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} \
          -e SPOTIFY_REDIRECT_URI=${{ secrets.SPOTIFY_REDIRECT_URI }} \
          ghcr.io/conradludgate/spotify-auth-proxy:latest
          sleep 5  # Give the server a moment to start

      - name: Get Auth URL and API Key
        id: spotify_auth
        run: |
          AUTH_URL=$(curl -s http://localhost:27228/auth-url)
          echo "Auth URL: $AUTH_URL"
          echo "Please visit the Auth URL and complete the authentication process"
          echo "Waiting for authentication..."
          API_KEY=$(curl -s --retry 30 --retry-delay 10 http://localhost:27228/api-key)
          echo "::add-mask::$API_KEY"
          echo "SPOTIFY_API_KEY=$API_KEY" >> $GITHUB_ENV

      - name: Apply Terraform
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true
          variables: |
            spotify_api_key = "${{ env.SPOTIFY_API_KEY }}"

      - name: Stop Spotify Auth Proxy
        if: always()
        run: docker stop spotify-auth-proxy
