name: Update playlist with Spotify Auth

on:
  push:
    branches:
      - main

jobs:
  spotify-auth-and-apply:
    runs-on: ubuntu-latest  
    name: Apply
    steps:
    - name: Install Go
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.16.0'
    - run: go get -u github.com/conradludgate/terraform-provider-spotify/spotify_auth_proxy
    - run: spotify_auth_proxy
    
    

    
