name: Update playlist with Spotify Auth

on:
  push:
    branches:
      - main

jobs:
  spotify_auth_and_apply:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/conradludgate/spotify-auth-proxy:latest
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
      ports:
        - 27228:27228

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Spotify Auth Proxy
        run: |
          /app/spotify-auth-proxy &
          sleep 5  # Give the server a moment to start

      - name: Get Auth URL and API Key
        id: spotify_auth
        run: |
          AUTH_URL=$(curl -s http://localhost:27228/auth-url)
          echo "Auth URL: $AUTH_URL"
          echo "Please visit the Auth URL and complete the authentication process"
          echo "Waiting for authentication..."
          API_KEY=$(curl -s http://localhost:27228/api-key)
          echo "::add-mask::$API_KEY"
          echo "SPOTIFY_API_KEY=$API_KEY" >> $GITHUB_ENV

      - name: Apply Terraform
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true
          variables: |
            spotify_api_key = "${{ env.SPOTIFY_API_KEY }}"
