name: Update playlist

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start Auth Server
        run: |
          docker run --rm -i -p 27228:27228 --env SPOTIFY_CLIENT_REDIRECT_URI= ${{ secrets.SPOTIFY_CLIENT_REDIRECT_URI }} --env SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} --env SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} ghcr.io/conradludgate/spotify-auth-proxy
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true
          variables: |
                    spotify_api_key = "xx"
