name: Update playlist

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform
    env:
      # Set environment variables here
      PORT: 27228
      AUTH_PROXY_IMAGE: ghcr.io/conradludgate/spotify-auth-proxy
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Spotify Auth Proxy
        id: spotify-auth-proxy
        run: |
          docker run --rm -it -p $PORT:$PORT --env-file ./.env $AUTH_PROXY_IMAGE > output.log 2>&1 &
          sleep 10
          AUTH_URL=$(grep -o 'http://[^ ]*' output.log)
          echo "Auth URL: $AUTH_URL"
          echo "::set-output name=auth_url::$AUTH_URL"

      - name: Authenticate and Get API Key
        id: get-api-key
        run: |
          # This is a placeholder for manual authentication step.
          # In a real-world scenario, you might need to automate this with a headless browser or manually perform the authentication.
          echo "Please authenticate using the following URL: ${{ steps.spotify-auth-proxy.outputs.auth_url }}"
          read -p "Enter the API Key: " API_KEY
          echo "::add-mask::$API_KEY"
          echo "::set-output name=api_key::$API_KEY"

      - name: Save API Key to GitHub Secrets
        run: |
          gh secret set SPOTIFY_API_KEY -b"${{ steps.get-api-key.outputs.api_key }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true
          variables: |
            spotify_api_key = "${{ secrets.SPOTIFY_API_KEY }}"
